name: genshin_mod_manager
description: Genshin mod manager.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.5.8

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  archive: ^3.6.1
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  cp949_codec: ^1.0.2
  desktop_drop: ^0.5.0
  envied: ^0.5.4+1
  ffi: ^2.1.3
  filepicker_windows: ^2.1.4
  fluent_ui: ^4.9.1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_hooks: ^0.20.5
  flutter_image_converter: ^0.3.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.2
  http: ^1.2.2
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  meta: ^1.15.0
  package_info_plus: ^8.0.2
  pasteboard: ^0.3.0
  path: ^1.9.0
  protocol_handler: ^0.2.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  watcher: ^1.1.0
  win32: ^5.5.4
  window_manager: ^0.4.2

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  dependency_validator: ^4.1.0
  envied_generator: ^0.5.4+1
  flutter_lints: ^4.0.0
  flutter_oss_licenses: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  plugin_platform_interface: ^2.1.8
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  url_launcher_platform_interface: ^2.3.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/
