name: genshin_mod_manager
description: Genshin mod manager.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.3+3

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  archive: ^3.4.10
  collection: ^1.18.0
  desktop_drop: ^0.4.4
  ffi: ^2.1.2
  filepicker_windows: ^2.1.0
  fluent_ui: ^4.8.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  go_router: ^13.2.1
  hooks_riverpod: ^2.5.1
  http: ^1.2.0
  json_annotation: ^4.8.1
  logger: ^2.1.0
  meta: ^1.11.0
  package_info_plus: ^6.0.0
  pasteboard: ^0.2.0
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  watcher: ^1.1.0
  win32: ^5.3.0
  window_manager: ^0.3.8

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  dependency_validator: ^3.2.3
  flutter_lints: ^3.0.1
  flutter_oss_licenses: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  plugin_platform_interface: ^2.1.8
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  url_launcher_platform_interface: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - images/
