name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
          architecture: x64
      - run: flutter build windows
      - run: move build\windows\x64\runner\Release GenshinModManager
      - run: tar -acf GenshinModManager.zip GenshinModManager
      - run: certutil -hashfile GenshinModManager.zip SHA256
      - uses: actions/upload-artifact@v2
        with:
          name: Binary Artifact
          path: GenshinModManager.zip
          retention-days: 1
          if-no-files-found: error
