on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'LICENSE'
      - '*.md'
    

jobs:
  flutter-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2

    - name: Flutter test
      run: flutter test