on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - ".github/**"
      - ".readme/**"
      - ".gitignore"
      - "LICENSE"
      - "*.md"

jobs:
  flutter-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up secret file
        run: |
          echo @'
          ${{ secrets.REMOTE_SECRET }}
          '@ > .env

      - uses: subosito/flutter-action@v2

      - name: Flutter pub get
        run: flutter pub get

      - name: Run build_runner
        run: dart run build_runner build -d

      - name: Generate flutter l10n
        run: flutter gen-l10n

      - name: Flutter test
        run: flutter test
