on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - labeled
      - unlabeled


jobs:
  pr-label-check:
    runs-on: ubuntu-latest

    steps:
    - run: |
        if [[ ${{contains(github.event.pull_request.labels.*.name, 'release') && contains(github.event.pull_request.labels.*.name, 'build')}} == "true" ]]; then
          echo "This PR has both 'release' and 'build' labels. Those labels are mutually exclusive."
          exit 1
        fi