on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

concurrency:
  group: pr-version-increment-check-${{ github.sha }}
  cancel-in-progress: true

jobs:
  check_version_increment:
    if: contains(github.event.pull_request.labels.*.name, 'release') || contains(github.event.pull_request.labels.*.name, 'build')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT

      - uses: subosito/flutter-action@v2

      - name: Install cider
        run: flutter pub global activate cider

      - name: Get the head version
        id: get_head_version
        run: |
          HEAD_OUTPUT=$(cider version)
          echo "HEAD_OUTPUT=v$HEAD_OUTPUT" >> $GITHUB_OUTPUT

      - name: Check version increment
        run: |
          if [ ${{ steps.get_head_version.outputs.HEAD_OUTPUT }} == ${{ steps.get_latest_tag.outputs.LATEST_TAG }} ]; then
            echo "Version number has not changed in the PR."
            exit 1
          fi
