name: PR label check

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - labeled
      - unlabeled


jobs:
  check:
    name: PR label validation
    runs-on: ubuntu-latest

    steps:
    - name: Check for PR tag
      run: |
        if [[ ${{contains(github.event.pull_request.labels.*.name, 'release') && contains(github.event.pull_request.labels.*.name, 'build')}} == "true" ]]; then
          exit 1
        fi